spring:
  application:
    name: test-application
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


springdoc:
  swagger-ui:
    use-root-path: true
#    default-models-expand-depth: -1
  version: '@springdoc-openapi-starter-webmvc-ui.version@'